---
- name: Deploy Docker Compose for web application
  block:
    - name: Copy Docker Compose template
      template:
        src: docker-compose.yml.j2
        dest: "{{ web_app_compose_path }}/docker-compose.yml"

    - name: Ensure Docker Compose is installed
      pip:
        name: docker-compose
        state: present

    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: "{{ web_app_compose_path }}"
  tags:
    - deploy

- include_tasks: 0-wipe.yml
  when: web_app_full_wipe
  tags:
    - wipe
